import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import Header from './../common/components/shared/header';
import ApolloProvider from '~/providers/apolloProvider';
import ReduxProvider from '~/providers/reduxProvider';
import SessionProvider from '~/providers/sessionProvider';
import 'react-date-range/dist/styles.css'; // main style file
import 'react-date-range/dist/theme/default.css';
import MenuDetails from '~/common/components/molecules/menuDetails';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  // const router = useRouter()

  return (
    <html lang="ar" dir="rtl">
      <body>
        <SessionProvider>
          <ApolloProvider>
            <ReduxProvider>
              {children}
              <MenuDetails/>

            </ReduxProvider>
          </ApolloProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
