import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../../common/components/shared/header";
import AuthProvider from "~/providers/authProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "لوحة التحكم",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const router = useRouter()

  return (
    <AuthProvider>
      <Header />
      <div className="page text-right main-content-wrap">
        <div className="separator-breadcrumb border-top"></div>
        <div className="p-4">{children}</div>
      </div>
    </AuthProvider>
  );
}
